### ISSUE TITLE
Add Katello support

### ISSUE THREAD

**Issue by ripcurld00d** [david-caro/python-foreman#25]
We are running a Python script in `Jenkins` to provision our hosts through `Foreman` using your `python-foreman`.
Now that we've moved some of our hosts to `Satellite 6`, it would be nicer to run `REST` requests that communicate with the `Katello`[*] through `python-foreman` instead of using `requests` API.

[*] we want to install the `operating system` from a given `content view`.

**Comment by ripcurld00d** [comment]
It probably will be a better idea to fork this as another module (e.g. python-satellite).

**Comment by david-caro** [comment]
What is exactly the difference on the paths? Maybe we can just separate the lib in two (python-apipie and python-foreman) or something, so we can reuse the code for both

**Comment by ripcurld00d** [comment]
IIRC:
* Katello: <url>/katello/api/v<version-number>/<resource>
* Foreman: <url>/api/v<version-number>/<resource>
