### ISSUE TITLE
Host creation error with 'host_parameters_attributes'

### ISSUE THREAD

**Issue by amith-reddy** [david-caro/python-foreman#33]
When i try to create host with below parameters, i get the unknown attribute error. I am trying to add custom host parameter attribute 'vm id'.

####################################
url = http://foremanstage1.ops.expertcity.com/api/hosts
headers = {'Content-Length': '292', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json; version=2', 'User-Agent': 'python-requests/2.5.1 CPython/2.7.5 Linux/2.6.32-504.el6.x86_64', 'Connection': 'keep-alive', 'Cookie': '_session_id=BAh7CEkiD3Nlc3Npb25faWQGOgZFRkkiJWUxNDIxZWU2MGY4OTEzYTcyNGQ3OGYzYWMxMjVhMzdmBjsAVEkiEW9yaWdpbmFsX3VyaQY7AEYiFC91c2Vycy9leHRsb2dpbkkiC2xvY2FsZQY7AEZJIgdlbgY7AEY%3D--4399c6ed29c3995c918d9e26ee7b57ff0a8e8d22', 'Content-type': 'application/json', 'Authorization': '*****'}
-------- data sent -----------------
{"host": {"operatingsystem_id": 14, "environment_id": 4, "name": "amithf", "medium_id": 3, "subnet_id": 1, "ip": "10.229.70.187", "hostgroup_id": 96, "mac": "06:44:4e:00:06:88", "architecture_id": 1, "host_parameters_attributes": [{"vm_id": "QAI:105546"}], "domain_id": 2688, "ptable_id": 1}}

==================

@@@@@ response @@@@@@@@@@@@@@@@
headers = {'status': '500 Internal Server Error', 'x-request-id': '4d66013ad42c13d198002c2f39dced39', 'x-powered-by': 'Phusion Passenger 4.0.18', 'transfer-encoding': 'chunked', 'set-cookie': '_session_id=BAh7CEkiD3Nlc3Npb25faWQGOgZFRkkiJWUxNDIxZWU2MGY4OTEzYTcyNGQ3OGYzYWMxMjVhMzdmBjsAVEkiEW9yaWdpbmFsX3VyaQY7AEYiFC91c2Vycy9leHRsb2dpbkkiC2xvY2FsZQY7AEZJIgdlbgY7AEY%3D--4399c6ed29c3995c918d9e26ee7b57ff0a8e8d22; path=/; HttpOnly', 'foreman_version': '1.7.1', 'connection': 'close', 'server': 'Apache/2.2.15 (Red Hat)', 'x-runtime': '0.045447', 'x-ua-compatible': 'IE=Edge', 'cache-control': 'no-cache', 'date': 'Mon, 23 Mar 2015 21:04:17 GMT', 'apipie-checksum': '332cb2f58cb5663ef03d7f6512e4af2c', 'content-type': 'application/json; charset=utf-8', 'foreman_api_version': '2'}
code = 500
reason = Internal Server Error
--------- data received ------------
{
  "error": {"message":"unknown attribute: vm_id"}
}

**Comment by lukas-bednar** [comment]
Hi,
it doesn't work like this. you need to pass dictionary containing 'name' and 'value' keywords.

```
"host_parameters_attributes": [{
   'name': 'vm_id',
   'value': 'QAI:105546',
}]
```

**Comment by lukas-bednar** [comment]
I think this issue may be closed.

**Comment by david-caro** [comment]
Thanks Lukas
