### ISSUE TITLE
Hostgroups Index

### ISSUE THREAD

**Issue by xnaveira** [david-caro/python-foreman#35]
When trying to use the index method for the hostgroups:

    TypeError: index() takes at least 2 arguments (1 given)

If an argument is given (ie 'someargument') the following url gets queried:

     /api/puppetclasses/someargument/hostgroups

This is using Foreman 1.7.3 and use_cache=False upon object creation.

**Comment by lukas-bednar** [comment]
duplicated to https://github.com/david-caro/python-foreman/issues/26 ,
you can try patches mentioned in discussion.

**Comment by david-caro** [comment]
This is also fixed on #37
