### ISSUE TITLE
Missing tags? 

### ISSUE THREAD

**Issue by sdodson** [david-caro/python-foreman#74]
I can't find 0.4.1, 0.4.5, 0.4.11, 0.4.12 tags. Have they by chance not been pushed up to github?

**Comment by david-caro** [comment]
Not every version or release has a tag, but every commit has a different version. You can check the changelog to see which commits match which versions, if you have the git code, you can check with the version_manager.py script, running `scripts/version_manager.py . changelog`.

Cheers

**Comment by sdodson** [comment]
So, how do I work back from 0.4.11 to the commit it references? Do I just take the most recent hash in a given changelog entry?

```
$ scripts/version_manager.py . changelog
...
* 0.4.11 "David Caro <david@dcaro.es>"
    MINOR 3f6234e7: Merge pull request #73 from david-caro/remove_pbr
    MINOR 34eab999: packaging: deprecate py26 and move to setuptools
```

**Comment by david-caro** [comment]
You should take the merge commit there, the others are commits that are included on it (for the versioning it only takes into account the main parents path).

**Comment by david-caro** [comment]
Specifically in this case 3f6234e7. Completely agree though that it's not very clear, I will try to change the way the changelog is generated to make that more visible ;)

**Comment by sdodson** [comment]
Awesome, thanks!
