### ISSUE TITLE
/api/template/import breaks python-foreman

### ISSUE THREAD

**Issue by Ntr0** [david-caro/python-foreman#84]
MethodApiDescription.generate_func tries to generate a method "import" which leads to a syntax error. This could be fixed by renaming the function to "import_" in "MethodApiDescription._get_name" method.

**Comment by Ntr0** [comment]
I just realized that this is a duplicate of #77

**Comment by david-caro** [comment]
Yep :), there I was waiting for the api definition too, if you can pass it we can solve both at the same time.

**Comment by Ntr0** [comment]
Here it is. The API def is from foreman R1.15_RC2 & Katello R3.4 RC2 with some required & additional plugins.


[foreman_1.15_rc2.json.tar.gz](https://github.com/david-caro/python-foreman/files/983897/foreman_1.15_rc2.json.tar.gz)

**Comment by Ntr0** [comment]
Previous json was direct dump from foreman/apidoc. Here the tar gz from python-foreman cache.
Contains other foreman development versions as well. As stated above, katello is always integrated, as well as other plugins.

[foreman_1.14_1.15_api_def.tar.gz](https://github.com/david-caro/python-foreman/files/984070/foreman_1.14_1.15_api_def.tar.gz)

**Comment by Ntr0** [comment]
@david-caro Please tell me, if you want the api defs from python-cache in the pull request itself. I'm not sure about this, since the definitons contain endpoints from various optional plugins like katello, discovery etc. But if thats ok, I can add this easily.

**Comment by david-caro** [comment]
The issue is that they are quite big by themselves, so I don't think that it's nice to add them to the packaged, but we can try to add something minimal that reproduces the issue to a test in order to avoid regression, I did not have time to add it myself yet, probably during the weekend, but if you have some time I'll really appreciate it :)

**Comment by Ntr0** [comment]
So, finally here it is. Foreman vanilla R1.15.0-v1 Rest API doc.

[foreman_1.15.0-v1.tar.gz](https://github.com/david-caro/python-foreman/files/1054768/foreman_1.15.0-v1.tar.gz)

**Comment by Ntr0** [comment]
Bump
