### ISSUE TITLE
Can't figure out how to use `/api/hostgroups/:hostgroup_id/hosts`...

### ISSUE THREAD

**Issue by digitalfiz** [david-caro/python-foreman#89]
Is it possible with this module to use sub resources of a resource? I have tried many different ways and I can't figure it out :/

**Comment by digitalfiz** [comment]
Figured it out litterally 10 seconds after posting this :P its:

```python
f.hosts.index(hostgroup_id=hostgroup['id'])
```

**Comment by david-caro** [comment]
:+1:
